version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: black
      versions:
      - 21.4b0
      - 21.4b1
    - dependency-name: mkdocs-material
      versions:
      - 7.1.2
