---
services:

    traefik:
        restart: unless-stopped
        labels:
            traefik.http.routers.traefik-dashboard-http.rule: Host(`monitor.localhost`)
        command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
            - --providers.docker
      # Do not expose all Docker services, only the ones explicitely exposed
            - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
            - --entrypoints.http.address=:80
      # # Create an entrypoint "https" listening on port 443
      # - --entrypoints.https.address=:443
      # # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      # - --certificatesresolvers.le.acme.email=klimczak.mathieu@pm.me
      # # Store the Let's Encrypt certificates in the mounted volume
      # - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # # Use the TLS Challenge for Let's Encrypt
      # - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable the access log, with HTTP requests
            - --accesslog
      # Enable the Traefik log, for configurations and errors
            - --log
      # Enable the dashboard and API
            - --api.insecure
            - --api
