services:

  backend:
    ports:
      - 80:80

  uptime-kuma:
    ports:
      - 3001:3001

  db:
    ports:
      - 5432:5432

  db-monitoring:
    ports:
      - 5050:5050

networks:
  traefik-public:
    external: false