---
services:
    traefik:
            # Use the latest v2.x.x Traefik image available, check https://hub.docker.com/_/traefik?tab=tags
        image: traefik:v2.6.1
        container_name: traefik-reverse-proxy
        ports:
                  # Listen on port 80, default port for HTTP, necessary to redirect to HTTPS
            - 80:80
                  #port_outside_container:port_inside_container
                  # Listen on port 443, default for HTTPS
            - 443:443
            - 8080:8080
        labels:
                  # Enable Traefik for the traefik dashboard, to make it available in the public network
            traefik.enable: true
                  # Define the port inside of the Docker service to use
            traefik.http.services.traefik-dashboard.loadbalancer.server.port: 8080
                  # HTTP
                  # Make Traefik use this domain in HTTP
            traefik.http.routers.traefik-dashboard-http.entrypoints: http
                  # Use the traefik-public network (declared below)
            traefik.docker.network: traefik-public
        volumes:
                  # Add Docker sock as a mounted volume, so that Traefik can read the labels of the other services
            - /var/run/docker.sock:/var/run/docker.sock:ro       # Mount the volume (named volume) to store the certificates
            - traefik-public-certificates:/certificates
        command:
                  # Enable Docker in Traefik, so that it reads labels from Docker services
            - --providers.docker       # Do not expose all Docker services, only the ones explicitely exposed
            - --providers.docker.exposedbydefault=false       # Create an entrypoint "http" listening on port 80
            - --entrypoints.http.address=:80       # Enable the access log, with HTTP requests
            - --accesslog       # Enable the Traefik log, for configurations and errors
            - --log       # Enable the dashboard and API
            - --api
        networks:
                  # Use the public network created to be shared between Traefik and
                  # any other service that needs to be publicly available with https
            - traefik-public

volumes:
      # Create a volume to store the certificates, there is a constraint to make sure
      # Traefik is always deployed to the same Docker node with the same volume containing
      # the HTTPS vertificates
    traefik-public-certificates:


networks:
      # Use the previsouly created public network "traefik-public", shared with
      # other services that needs to be publicly available wia this Traefik
    traefik-public:
        external: true
