---
services:

    backend:
        container_name: fastapi

    frontend:
        container_name: streamlit

    db:
        image: postgres:14.2-bullseye
        container_name: postgre
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432
        networks:
            - db-network

    db-monitoring:
        image: dpage/pgadmin4:6.6
        container_name: pgadmin
        restart: always
        networks:
            - caddy-proxy-network
            - db-network
        depends_on:
            - db

    uptime-kuma:
        image: louislam/uptime-kuma
        container_name: uptime-kuma
        volumes:
            - uptime-kuma:/app/data
        networks:
            - caddy-proxy-network
volumes:
    uptime-kuma:
    postgres_data:


networks:
    backend-frontend:
    caddy-proxy-network:
        external: true
    db-network:
