---
x-db-env: &db-env
    POSTGRES_USER: ${DB_USERNAME}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: postgres
    POSTGRES_HOST: db
    POSTGRES_PORT: '5432'

x-db-monitoring-env: &db-monitoring-env
    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    PGADMIN_DEFAULT_PASSWORD: ${HASHED_PGADMIN_DEFAULT_PASSWORD}
    PGADMIN_LISTEN_PORT: 5050

services:

    backend:
        image: vorphus/api-prod:latest
        container_name: fastapi
        # yamllint disable-line rule:line-length
        command: gunicorn -c app/gunicorn.py -k uvicorn.workers.UvicornWorker app.main:app
        restart: always
        environment:
            <<: *db-env
            DEPLOYMENT_COMMIT: ${DEPLOYMENT_COMMIT}
            DEPLOYMENT_DATE: ${DEPLOYMENT_DATE}
        networks:
            - caddy-proxy-network
            - db-network
        depends_on:
            - db

    frontend:
        image: vorphus/ui-prod:latest
        container_name: streamlit
        # yamllint disable-line rule:line-length
        command: streamlit run frontend/main_page.py  # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0
        restart: always
        networks:
            - backend-frontend
            - caddy-proxy-network
        depends_on:
            - backend

    db:
        image: postgres:14.2-bullseye
        container_name: postgre
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            <<: *db-env
        networks:
            - db-network

    db-monitoring:
        image: dpage/pgadmin4:6.6
        container_name: pgadmin
        restart: always
        networks:
            - caddy-proxy-network
            - db-network
        depends_on:
            - db
        environment:
            <<: *db-monitoring-env

    uptime-kuma:
        image: louislam/uptime-kuma
        container_name: uptime_kuma
        restart: always
        volumes:
            - uptime-kuma:/app/data
        networks:
            - caddy-proxy-network

volumes:
    uptime-kuma:
    postgres_data:


networks:
    caddy-proxy-network:
        external: true
    db-network:
