services:

  traefik:
    restart: always
    labels:
      traefik.http.routers.traefik-dashboard-http.rule: Host(`monitor.mathieuklimczak.com`)
      # Use the traefik-public network (declared below)
      # HTTPS
      # Use https
      traefik.http.routers.traefik-dashboard-https.entrypoints: https
      traefik.http.routers.traefik-dashboard-https.rule: Host(`monitor.mathieuklimczak.com`)
      traefik.http.routers.traefik-dashboard-https.tls: true
      # Use the "le" (Let's Encrypt) resolver created below
      traefik.http.routers.traefik-dashboard-https.tls.certresolver: le
      # Use the special Traefik service api@internal with the web UI/dashboard
      traefik.http.routers.traefik-dashboard-https.service: api@internal
      # https-redirect middleware to redirect HTTP to HTTPS
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
      # Middlerware to redirect HTTP to HTTPS
      # Anything that happend to our app on HTTP will be redirect by the middlerware
      # above on HTTPS
      traefik.http.routers.traefik-dashboard-http.middlewares: https-redirect
      # admin-auth middleware with HTTP basic auth
      # Using the env varaables USERNAME and HASHED_PASSWORD
      traefik.http.middlewares.admin-auth.basicauth.users: ${USERNAME}:${HASHED_PASSWORD}
      # Enable HTTP Basic auth, using the middleware created above
      traefik.http.routers.traefik-dashboard-https.middlewares: admin-auth
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitely exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.le.acme.email=klimczak.mathieu@pm.me
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the dashboard and API
      - --api
