---
site_name: Production Stack Documentation
site_author: Mathieu Klimczak
theme:
  name: material
  logo: images/noun_Robot_1955251.svg
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer en mode sombre
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Basculer en mode clair
  font:
    text: Roboto
    code: JetBrains Mono Medium

plugins:
  - search:
      lang: fr

nav:
  - Accueil: index.md
  - HTTPS and Reverse proxy: https.md
  - FastAPI and Gunicorn: api.md
  - Postgre and pgadmin: db.md
  - Monitoring: monitoring.md
  - Authentication: auth.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - pymdownx.details
  - def_list
  - attr_list
  - md_in_html
  - meta
  - pymdownx.betterem:
      smart_enable: all
  # config pour latex
  - pymdownx.arithmatex:
      generic: true

# config pour latex
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
