name: Connect to a VPS and deploy a docker-compose stack

on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
      ssh_host:
        required: true
      ssh_username:
        required: true
      db_username:
        required: true
      db_password:
        required: true
      pgadmin_email:
        required: true
      pgadmin_password:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ssh_private_key }}" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ secrets.ssh_host }}
            User ${{ secrets.ssh_username }}
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
          END

      - name: Add deploy key to ssh-agent
        run: ssh staging 'eval "$(ssh-agent -s)" && ssh-add ~/.ssh/deploy && ssh-add -l -E md5 && cd code/stack_prod && git checkout main && git pull origin main && exit'

      - name: Update stack
        run:
          ssh staging 'export DB_USERNAME=${{ secrets.db_username }} && export DB_PASSWORD=${{ secrets.db_password }} && export PGADMIN_DEFAULT_EMAIL=${{ secrets.pgadmin_email }} && export HASHED_PGADMIN_DEFAULT_PASSWORD=${{ secrets.pgadmin_password }} && cd code/stack_prod && docker-compose -f docker-compose.yml up --build -d && exit'
