---
name: Build & Deploy PR
on: [pull_request]

env:
    API_NAME: api-prod
    UI_NAME: ui-prod

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ['3.8', '3.9']
                exclude:
                    - os: macos-latest
                      python-version: '3.8'

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Display Python version
              run: python --version

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r app/requirements.txt
                  python -m pip install -r frontend/requirements.txt
                  python -m pip install -r requirements-test.txt

            - name: Run test suite
              run: |
                  python -m pytest -v

    build-image:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build
              uses: docker/build-push-action@v3
              with:
                  file: Dockerfile.backend
                  push: false
                  tags: vorphus/${{ env.API_NAME }}:latest,vorphus/${{ API_NAME }}:${{ github.sha }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  file: Dockerfile.frontend
                  push: false
                  tags: vorphus/${{ UI_NAME }}:latest,vorphus/${{ UI_NAME }}:${{ github.sha }}

    build-docs:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.9'
            - name: Install dependencies
              run: |
                  python -m pip install -e ".[docs]" --no-cache-dir
            - name: Deploy documentation
              run: mkdocs gh-deploy --force
